export const contactOptions = [
    {
        name: 'Silver Gray',
        value: 'silver-gray',
        link: '',
        image: './images/.png',
        vibe: ['natural'],
        outfit: ['neutral', 'metallic'],
        isPrescripted: true,
        isAvailable: true,
    },
    {
        name: 'Glowy Natural',
        value: 'glowy-natural',
        link: '',
        image: './images/.png',
        vibe: ['natural'],
        outfit: ['neutral', 'warm tone', 'earth tone'],
        isPrescripted: false,
        isAvailable: true,
    },
    {
        name: 'Glowy Black',
        value: 'glowy-black',
        link: '',
        image: './images/.png',
        vibe: ['natural', 'bold'],
        outfit: ['neutral', 'warm tone', 'cool tone', 'metallic'],
        isPrescripted: false,
        isAvailable: true,
    },
    {
        name: 'Sweet Blush',
        value: 'sweet-blush',
        link: '',
        image: './images/.png',
        vibe: ['bold'],
        outfit: ['pinks', 'metallic'],
        isPrescripted: false,
        isAvailable: true,
    },
    {
        name: 'Rum Crunch',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['soft', 'natural'],
        outfit: ['warm tone', 'neutral', 'pinks'],
        isPrescripted: true,
        isAvailable: true,
    },
    {
        name: 'Light Brown',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['soft', 'natural'],
        outfit: ['warm tone', 'earth tone', 'neutral'],
        isPrescripted: true,
        isAvailable: true,
    },
    {
        name: 'Warm Pearl',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['soft', 'natural'],
        outfit: ['neutral', 'warm tone', 'earth tone', 'pinks'],
        isPrescripted: false,
        isAvailable: true,
    },
    {
        name: 'Field Blue',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['bold'],
        outfit: ['metallic', 'cool tone'],
        isPrescripted: false,
        isAvailable: true,
    },
    {
        name: 'Blue Purple',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['bold'],
        outfit: ['metallic', 'cool tone'],
        isPrescripted: false,
        isAvailable: true,
    },
    {
        name: 'Gray Blue',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['bold'],
        outfit: ['metallic', 'cool tone'],
        isPrescripted: true,
        isAvailable: true,
    },
    {
        name: 'Sunset Pink',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['soft', 'bold'],
        outfit: ['pinks', 'cool tone', 'metallic'],
        isPrescripted: true,
        isAvailable: true,
    },
    {
        name: 'Berry Pink',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['soft'],
        outfit: ['neutral', 'cool tone', 'pinks', 'metallic'],
        isPrescripted: true,
        isAvailable: true,
    },
    {
        name: 'Golden Olive',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['natural', 'soft'],
        outfit: ['warm tone', 'earth tone', 'neutral'],
        isPrescripted: true,
        isAvailable: true,
    },
    {
        name: 'Sweet Milk Tea',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['natural', 'soft'],
        outfit: ['warm tone', 'earth tone', 'neutral', 'pinks'],
        isPrescripted: true,
        isAvailable: true,
    },
    {
        name: 'Vivi Pink',
        value: '',
        link: '',
        image: './images/.png',
        vibe: ['soft', 'natural'],
        outfit: ['neutral', 'cool tone', 'pinks', 'metallic'],
        isPrescripted: true,
        isAvailable: false,
    },
]

// vibe:
// - soft 
// - bold 
// - natural

// outfit:
// - neutral
// - warm tone 
// - cool tone 
// - earth tone 
// - pinks 
// - metallic